import type { PluginBundle } from "./types";

export const housePlugin: PluginBundle = {
  id: "house-build",
  name_he: "בניית בית פרטי",
  name_en: "Owner-Builder House",
  description: "ניהול בניה פרטית: מטבח, אינסטלציה, גינון, מקלחות.",
  icon: "HardHat",
  ai_prompt_addendum:
    "ההקשר: המשתמש בונה בית פרטי בעצמו (Owner-Builder). הנחה שמנהלי האתר והפקחים נוטים להחמיץ פרטים. הגן על המשתמש דרך אימותים מובנים. הקפד על דחיפות במשימות קריטיות לפני שנקבעות 'עובדות בשטח' יקרות-שינוי.",
  color_palette: ["#f59e0b", "#0ea5e9", "#10b981", "#a855f7"],
  objectives: [
    {
      Objective_ID: "OBJ-201",
      Category: "מטבח ותכנון חלל",
      The_Goal:
        "תכנון מחדש של המטבח לניצול מיטבי של משטח השיש ופתרון בעיות זרימה, תוך עצירת עבודות בשטח למניעת פגיעה בתשתיות.",
      Priority_Level: "CRITICAL",
      Status: "ACTIVE",
    },
    {
      Objective_ID: "OBJ-202",
      Category: "אינסטלציה ואופטימיזציה",
      The_Goal: "הוזלת רכיב הקצה של המתיזן בשירותים עקב היעדר תשתית מים חמים בשטח.",
      Priority_Level: "LOW",
      Status: "ACTIVE",
    },
    {
      Objective_ID: "OBJ-203",
      Category: "פיתוח חוץ וגינון",
      The_Goal:
        "הקמת מערכת השקיה ממוחשבת מפוצלת (עצי פרי, דשא, ירק) עם תשתית חשמל ייעודית צמודה לברז.",
      Priority_Level: "HIGH",
      Status: "ACTIVE",
    },
    {
      Objective_ID: "OBJ-204",
      Category: "תכנון מקלחות ואינסטלציה",
      The_Goal:
        "בחינת היתכנות והחלטה לגבי הוספת אמבטיה במקלחת הורים (משפיע על מיקומי ניקוז וברזים בשטח).",
      Priority_Level: "HIGH",
      Status: "ACTIVE",
    },
  ],
  tasks: [
    {
      Task_ID: "TSK-301",
      Description:
        "פנייה דחופה להנהלת הפרויקט לעצירת עבודות אינסטלציה וחשמל במטבח למשך השבוע הקרוב",
      Status: "Pending",
      Blocked_By_Task_ID: "NONE",
      AI_Urgency_Level: "CRITICAL",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-03T12:00:00Z",
      relations: [],
      color: "#ef4444",
    },
    {
      Task_ID: "TSK-302",
      Description: "פגישה ביומן עם מעצב מטבחים אלטרנטיבי א'",
      Status: "Pending",
      Blocked_By_Task_ID: "TSK-301",
      AI_Urgency_Level: "HIGH",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-05T16:00:00Z",
      relations: [{ kind: "before", task_id: "TSK-301" }],
      color: "#f59e0b",
    },
    {
      Task_ID: "TSK-303",
      Description: "פגישה ביומן עם מעצב מטבחים אלטרנטיבי ב'",
      Status: "Pending",
      Blocked_By_Task_ID: "TSK-301",
      AI_Urgency_Level: "HIGH",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-07T11:00:00Z",
      relations: [{ kind: "before", task_id: "TSK-301" }],
      color: "#f59e0b",
    },
    {
      Task_ID: "TSK-305",
      Description: "רכישת ברז מתיזן פשוט (שליטה בעוצמה בלבד) לשירותים",
      Status: "Pending",
      Blocked_By_Task_ID: "NONE",
      AI_Urgency_Level: "LOW",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-15T00:00:00Z",
      relations: [],
      color: "#10b981",
    },
    {
      Task_ID: "TSK-306",
      Description: "בדיקה פיזית של נקודת חשמל אטומה סמוכה לברז הגינה",
      Status: "Pending",
      Blocked_By_Task_ID: "NONE",
      AI_Urgency_Level: "HIGH",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-06T08:00:00Z",
      relations: [],
      color: "#0ea5e9",
    },
    {
      Task_ID: "TSK-307",
      Description: "התייעצות עם אבא לגבי מפרט מערכת ההשקיה",
      Status: "Pending",
      Blocked_By_Task_ID: "NONE",
      AI_Urgency_Level: "MEDIUM",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-04T20:00:00Z",
      relations: [],
      color: "#0ea5e9",
    },
    {
      Task_ID: "TSK-309",
      Description: "שיחה לגבי בניית אמבטיה במקלחת הורים (לפני סגירת אינסטלציה)",
      Status: "Pending",
      Blocked_By_Task_ID: "NONE",
      AI_Urgency_Level: "HIGH",
      Snooze_Counter: 0,
      Re_Evaluate_Timestamp: "2026-06-04T18:00:00Z",
      relations: [],
      color: "#a855f7",
    },
  ],
  decisions: [
    {
      Decision_ID: "DEC-301",
      Topic: "עיכוב שלד מול שינוי תוכנית מטבח",
      Final_Choice_Made: "הקפאת עבודות שטח במטבח לטובת סבב מעצבים",
      Rationale_Short_vs_Long_Term:
        "טווח קצר: סיכון מול מנהל העבודה. טווח ארוך: משטח עבודה לא יעיל יגרום לעוגמת נפש יומיומית.",
      Linked_Advice_ID: "NONE",
    },
  ],
  advice: [],
};
