/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/decisions': typeof DecisionsRoute
  '/graph': typeof GraphRoute
  '/objectives': typeof ObjectivesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/decisions': typeof DecisionsRoute
  '/graph': typeof GraphRoute
  '/objectives': typeof ObjectivesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/decisions': typeof DecisionsRoute
  '/graph': typeof GraphRoute
  '/objectives': typeof ObjectivesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilot'
    | '/decisions'
    | '/graph'
    | '/objectives'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/copilot' | '/decisions' | '/graph' | '/objectives' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/copilot'
    | '/decisions'
    | '/graph'
    | '/objectives'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  DecisionsRoute: typeof DecisionsRoute
  GraphRoute: typeof GraphRoute
  ObjectivesRoute: typeof ObjectivesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  DecisionsRoute: DecisionsRoute,
  GraphRoute: GraphRoute,
  ObjectivesRoute: ObjectivesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
